## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Fri Oct 25 21:53:04 2024
## 
set sdc_version 1.4
current_design SYS_TOP
create_clock [get_ports {scan_clk}]  -name DFTCLK -period 20 -waveform {0 10}
set_clock_latency -min 0 [get_clocks {DFTCLK}]
set_clock_latency -max 0 [get_clocks {DFTCLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {DFTCLK}]
create_clock [get_ports {UART_CLK}]  -name UART_CLK -period 271.267 -waveform {0 135.634}
set_clock_latency -min 0 [get_clocks {UART_CLK}]
set_clock_latency -max 0 [get_clocks {UART_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {UART_CLK}]
create_clock [get_ports {REF_CLK}]  -name REF_CLK -period 20 -waveform {0 10}
set_clock_latency -min 0 [get_clocks {REF_CLK}]
set_clock_latency -max 0 [get_clocks {REF_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {REF_CLK}]
create_generated_clock -name ALU_CLK -source [get_ports {REF_CLK}] -divide_by 1 -master_clock [get_clocks {REF_CLK}] -add [get_pins {U13_CLK_GATE/U0_TLATNCAX12M/ECK}]
create_generated_clock -name TX_CLK -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_CLK}] -add [get_pins {U6_CLK_DIV_TX/U22/Y}]
create_generated_clock -name RX_CLK -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_CLK}] -add [get_pins {U8_CLK_DIV_RX/U34/Y}]
set_propagated_clock  [get_pins {U13_CLK_GATE/U0_TLATNCAX12M/ECK}]
set_propagated_clock  [get_pins {U6_CLK_DIV_TX/U22/Y}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_ports {REF_CLK}]
set_propagated_clock  [get_pins {U8_CLK_DIV_RX/U34/Y}]
set_clock_latency -min 0 [get_clocks {ALU_CLK}]
set_clock_latency -max 0 [get_clocks {ALU_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {ALU_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {ALU_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {ALU_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {ALU_CLK}]
set_clock_latency -min 0 [get_clocks {TX_CLK}]
set_clock_latency -max 0 [get_clocks {TX_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {TX_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {TX_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {TX_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {TX_CLK}]
set_clock_latency -min 0 [get_clocks {RX_CLK}]
set_clock_latency -max 0 [get_clocks {RX_CLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {RX_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {RX_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {RX_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {RX_CLK}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {test_mode}]
set_load -pin_load -max  0.5  [get_ports {SO[3]}]
set_load -pin_load -min  0.5  [get_ports {SO[3]}]
set_load -pin_load -max  0.5  [get_ports {SO[2]}]
set_load -pin_load -min  0.5  [get_ports {SO[2]}]
set_load -pin_load -max  0.5  [get_ports {SO[1]}]
set_load -pin_load -min  0.5  [get_ports {SO[1]}]
set_load -pin_load -max  0.5  [get_ports {SO[0]}]
set_load -pin_load -min  0.5  [get_ports {SO[0]}]
set_load -pin_load -max  0.5  [get_ports {UART_TX_O}]
set_load -pin_load -min  0.5  [get_ports {UART_TX_O}]
set_load -pin_load -max  0.5  [get_ports {parity_error}]
set_load -pin_load -min  0.5  [get_ports {parity_error}]
set_load -pin_load -max  0.5  [get_ports {framing_error}]
set_load -pin_load -min  0.5  [get_ports {framing_error}]
set_case_analysis 0 [get_ports {SE}]
set_case_analysis 0 [get_ports {test_mode}]
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max -name tsmc13_wl30
set_wire_load_model -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min -name tsmc13_wl30
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SI[3]}]
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SI[1]}]
set_input_delay -add_delay 54.2535 -clock [get_clocks {RX_CLK}] [get_ports {UART_RX_IN}]
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SE}]
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {test_mode}]
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SI[2]}]
set_input_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SI[0]}]
set_output_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SO[2]}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {TX_CLK}] [get_ports {parity_error}]
set_output_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SO[0]}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {TX_CLK}] [get_ports {UART_TX_O}]
set_output_delay -add_delay 54.2535 -clock [get_clocks {TX_CLK}] [get_ports {framing_error}]
set_output_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SO[3]}]
set_output_delay -add_delay 4 -clock [get_clocks {DFTCLK}] [get_ports {SO[1]}]
set_clock_uncertainty 0.1 -hold [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {REF_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {REF_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {TX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {TX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {DFTCLK}]
set_clock_uncertainty 0.025 -setup [get_clocks {DFTCLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {RX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {RX_CLK}]
set_clock_groups -name REF_CLK_1 -asynchronous  -group  [get_clocks {ALU_CLK REF_CLK}] -group  [get_clocks {RX_CLK TX_CLK UART_CLK}] -group  [get_clocks {DFTCLK}]
